server:
  port: 8082

spring:
  application:
    name: product-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=livestock_dev
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      username: postgres
      password: postgres
      connection-timeout: 10000
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 60000
      max-lifetime: 180000
      auto-commit: true
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: livestock_dev
        format_sql: true
        jdbc:
          batch_size: 15
          fetch_size: 90
        max_fetch_depth: 3
        generate_statistics: false
        temp:
          use_jdbc_metadata_defaults: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/dev/changelog.yaml
    liquibase-schema: livestock_dev_liquibase
    default-schema: livestock_dev
    drop-first: false

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

logging:
  config: classpath:logback-dev.xml

springdoc:
  enabled: true
  swagger-ui:
    enabled: true
    url: openapi.yaml
    tryItOutEnabled: true
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true

management:
  endpoints:
    enabled-by-default: false