openapi: 3.0.3
info:
  title: Product service
  description: |-
    Product service for the 'Livestock shop' project.
  contact:
    name: Luke Sukhanov
    email: lukesukhanov@gmail.com
    url: https://github.com/lukesukhanov
  version: "1.0"
servers: 
- url: http://127.0.0.1:8082
paths:
  /products:
    get:
      tags:
      - Products
      summary: Get products using paging and filtering
      parameters:
      - in: query
        name: page
        description: The required page
        required: false
        schema:
          type: integer
          format: int32
      - in: query
        name: size
        description: The page size 
        required: false
        schema:
          type: integer
          format: int32
      - in: query
        name: category
        description: The product category
        required: false
        schema:
          type: string
      - in: query
        name: minPrice
        description: The minimal price of a product
        required: false
        schema:
          type: number
          format: double
      - in: query
        name: maxPrice
        description: The maximal price of a product
        required: false
        schema:
          type: number
          format: double
      responses:
        200:
          description: Normal response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductsPage"
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        productName:
          type: string
          example: Овцы бараны
        description:
          type: string
          example: Продаю баранов и овец
        quantity:
          type: integer
          format: int32
          example: 57
        price:
          type: number
          format: double
          example: 9500
        currency:
          type: string
          example: RUB
        category:
          type: string
          example: Овцы
    ProductsPage:
      type: object
      properties:
        content:
          $ref: "#/components/schemas/Product"
        numberOfElements:
          type: integer
          format: int32
          example: 5
        first:
          type: boolean
          example: true
        last:
          type: boolean
          example: false
        totalElements:
          type: integer
          format: int32
          example: 10
        totalPages:
          type: integer
          format: int32
          example: 2